# Generated by Django 2.2.18 on 2021-02-04 00:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('published_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date (YYYY-MM-DD)')),
                ('photo', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='', verbose_name='Image')),
                ('counter_popularity', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Views')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='booking',
            name='f_category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='booking.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='booking',
            name='f_user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
