# Generated by Django 2.1.1 on 2019-04-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190421_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=16, verbose_name='Κωδικός πρόσβασης'),
        ),
    ]
